### ISSUE TITLE
Cloning of Microsoft/TypeScript-Handbook fails (unauthorized)

### ISSUE THREAD

**Issue by koalabi** [kjarmicki/typescript-handbook-to-pdf#1]
(Well, first of all, thanks for this nice tool - I had a similar need for having a PDF version of the Handbook with me)
As currently in the repo, the tool does not work anymore: cloning of the Handbook fails.
Actually, using a user is not needed. By modifying the buildUrl function in github.ts, the program work again:

 function buildUrl(repo: string): string {
        return `https://github.com/${repo}.git`;
    }

(So this issue also contains its fix ;-) )

**Comment by kjarmicki** [comment]
Oh, I haven't noticed this issue, sorry! Thanks and the PR that fixes it is now pulled in :)
