### ISSUE TITLE
Support for windows

### ISSUE THREAD

**Issue by xanatos** [kjarmicki/typescript-handbook-to-pdf#4]
There seems to be a problem in Windows: you are using the `rm -rf` command to remove the old folder in the github.ts, but it isn't supported under windows. Some suggestions about how to do it: https://stackoverflow.com/questions/18052762/remove-directory-which-is-not-empty . I've added a pull request with the changes.

**Comment by kjarmicki** [comment]
Resolved with #5, thanks again :)
