### ISSUE TITLE
Support for Linux

### ISSUE THREAD

**Issue by sam-artuso** [kjarmicki/typescript-handbook-to-pdf#6]
It would be great to have this working on Linux!

**Comment by kjarmicki** [comment]
It definitely should, especially since I have developed it using Ubuntu :thinking: 
What's your distribution and what incorrect behavior have you encountered while using this tool?

**Comment by antonio-piha** [comment]
@sam-artuso  don't forget to do this before running `npm start`:
- install Node.js (npm comes with it) [https://nodejs.org/en/download/](https://nodejs.org/en/download/)
- run `npm install` inside directory where this repo is downloaded and extracted

Then you can run `npm start`. It works on linux and everywhere Node.js can run.
